#!/bin/bash
rm -rf /usr/share/lilac/GuoyiPackages/guoyi/*/src
python /usr/share/lilac/GuoyiPackages/lilac-cleaner -f
python /usr/share/lilac/GuoyiPackages/repocleaner
chown -R guoyi:pkg /usr/share/lilac/GuoyiPackages
